# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
- task: Docker@2
  inputs:
    containerRegistry: 'Aqua Registry'
    command: 'login'
- task: aquasecScanner@4
  inputs:
    image: 'centos:latest'
    scanType: 'hosted'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'registry.aquasec.com/scanner:6.5'
    registry: 'Docker Hub'
    connection: 'AquaConsole-Scanner-ADM-ESE'