# Docker
- task: aquasecScanner@4
  inputs:
    image: 'centos:latest'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    registry: 'Docker Hub'
    connection: 'Aqua Demo Console'
