# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Aqua Registry'
    command: 'login'
- task: aquasecScanner@4
  inputs:
    image: 'centos:latest'
    scanType: 'hosted'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'registry.aquasec.com/scanner:6.5'
    runOptions: '-e AQUA_TOKEN=61ce5875ccd5e024bf51b1c9a4cf3534522f3d9b'
    registry: 'Docker'
    connection: 'AquaScannerSaaS'