- task: aquasecScanner@4
  inputs:
    image: 'centos:latest'
    scanType: 'hosted'
    register: true
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'registry.aquasec.com/scanner:6.5'
    registry: 'https://docker.io'
    connection: 'AquaConsole-Scanner'